---
- name: Build GCP environment
  hosts: gcp_vpc
  connection: local
  gather_facts: no
  force_handlers: True
  vars_files:
    - gcp_account_info.yml
  tasks:
    - name: Read the Vault Encrypted JSON file
      copy:
        content: "{{ lookup('file', 'credentials.json') }}"
        dest: "{{ service_account_file }}"
      notify: Clean tmp Decrypted Files
      tags: always

    - name: Get Subnet Facts
      gcp_compute_subnetwork_facts:
        region: "{{ subnets | map(attribute='region') | list | first }}"
        auth_kind: "{{ auth_kind }}"
        project: "{{ project }}"
        service_account_file: "{{ service_account_file }}"
      register: gcp_vpc_subnets
    - name: Validate all Subnets are Deployed
      assert:
        that:
          - gcp_vpc_subnets['items'] | selectattr('name', 'equalto', item.name) | map(attribute='ipCidrRange') | list | first == item.cidr
      loop: "{{ subnets }}"
  
  handlers:
    - name: Clean tmp Decrypted Files
      file:
        path: "{{ service_account_file }}"
        state: absent