---
- name: Ping Hosts
  hosts: all
  gather_facts: no
  force_handlers: true
  tasks:
    # - name: Removing Production Server 1 from Pools
    #   ping:
    #   when: inventory_hostname == 'lb-server'

    - name: Updating App in Production Server
      docker_container:
        name: go-recipes-api
        image: "khhini/go-recipes-api:{{IMAGE_TAG}}"
        state: stopped
        recreate: yes
        env: 
          REDIS_SERVER: "{{REDIS_SERVER}}"
          JWT_SECRET: "{{JWT_SECRET}}"
          MONGO_URI: "{{MONGO_URI}}"
          MONGO_DATABASE: "{{MONGO_DATABASE}}"
        published_ports:
          - 80:8080
      when: inventory_hostname == 'prod-server-1'

    - name: Checking App in Production Server 1 Ready for Handling Request
      uri:
        url: localhost
      when: inventory_hostname == 'prod-server-1'
    
    # - name: Add Production Server 1 to Pools and Removing Production Server 1 from Pools
    #   ping:
    #   when: inventory_hostname == 'lb-server'

    - name: Updating App in Production Server 2
      docker_container:
        name: go-recipes-api
        image: "khhini/go-recipes-api:{{IMAGE_TAG}}"
        state: started
        recreate: yes
        env: 
          REDIS_SERVER: "{{REDIS_SERVER}}"
          JWT_SECRET: "{{JWT_SECRET}}"
          MONGO_URI: "{{MONGO_URI}}"
          MONGO_DATABASE: "{{MONGO_DATABASE}}"
        published_ports:
          - 80:8080
      when: inventory_hostname == 'prod-server-2'

    - name: Checking App in Production Server 2 Ready for Handling Request
      uri:
        url: localhost
      when: inventory_hostname == 'prod-server-2'

    # - name: Add Production Server 2 to Pools
    #   ping:
    #   when: inventory_hostname == 'lb-server'