---
- name: Ping Hosts
  hosts: all
  gather_facts: no
  force_handlers: true
  tasks:
    - name: Disable server in 'www' backend pool
      community.general.haproxy:
        state: disabled
        host: prod-server-1
        backend: prod_back
      when: inventory_hostname == 'prod-server-1' 

    - name: Updating App in Production Server
      docker_container:
        name: go-recipes-api
        image: "khhini/go-recipes-api:{{IMAGE_TAG}}"
        state: started
        recreate: yes
        env: 
          REDIS_SERVER: "{{REDIS_SERVER}}"
          JWT_SECRET: "{{JWT_SECRET}}"
          MONGO_URI: "{{MONGO_URI}}"
          MONGO_DATABASE: "{{MONGO_DATABASE}}"
        published_ports:
          - 80:8080
      register: prod1_deployment
      when: inventory_hostname == 'prod-server-1' and disabled_prod1 is succeeded

    - name: Checking App in Production Server 1 Ready for Handling Request
      uri:
        url: http://prod-server-2/hallo
      register: prod1_hc
      when: inventory_hostname == 'lb-server' and prod1_deployment is succeeded
    
    # - name: Add Production Server 1 to Pools and Removing Production Server 1 from Pools
    #   ping:
    #   when: inventory_hostname == 'lb-server'

    - name: Updating App in Production Server 2
      docker_container:
        name: go-recipes-api
        image: "khhini/go-recipes-api:{{IMAGE_TAG}}"
        state: started
        recreate: yes
        env: 
          REDIS_SERVER: "{{REDIS_SERVER}}"
          JWT_SECRET: "{{JWT_SECRET}}"
          MONGO_URI: "{{MONGO_URI}}"
          MONGO_DATABASE: "{{MONGO_DATABASE}}"
        published_ports:
          - 80:8080
      register: prod2_deployment
      when: inventory_hostname == 'prod-server-2' and prod1_hc is succeeded

    - name: Checking App in Production Server 2 Ready for Handling Request
      uri:
        url: http://prod-server-2/hallo
      register: prod2_hc
      when: inventory_hostname == 'lb-server' and prod2_deployment is succeeded

    # - name: Add Production Server 2 to Pools
    #   ping:
    #   when: inventory_hostname == 'lb-server'